--- # This playbooks installs and configures Cockpit on Red Hat Enterprise Linux 7.9 on Port 3389 while configuring SELinux and Firewalld.
- name: Cockpit Setup and Configuration
  hosts: all
  become: true
  become_method: sudo
  tasks:
  # Install Cockpit and Cockpit Modules.
  - name: Yum Install
    ansible.builtin.yum:
      name:
      - cockpit
      - cockpit-dashboard
      - cockpit-storaged 
      state: latest
      update_cache: yes
  # Change Port in cockpit.socket file.
  - name: Set Port
    tags: port
    lineinfile:
     path: /usr/lib/systemd/system/cockpit.socket
     regexp: "ListenStream=9090"
     line: "ListenStream=3389"
     state: present
     backup: yes
    register: portout
  # Start Cockpit.
  - name: Start Cockpit
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    loop:
       - cockpit
       - 'cockpit.socket'
  # SELinux - Enable Cockpit to listen on Port.
  - name: SELinux - Allow Cockpit to listen on tcp port 3389
    community.general.seport:
     ports: 3389
     porto: tcp
     setype: websm_port_t
     state: present
     ignore_errors: yes
     when: ansible_selinux.status == "enabled"
  # Firewalld - Enable Cockpit to listen on Port.
  - name: Firewalld - Allow Cockpit to listen on tcp port 3389
    ansible.posix.firewalld:
     port: 3389/tcp
     permanent: yes
     immediate: yes
     state: enabled
     ignore_errors: yes
     notify: reload firewalld
  # Check and output Status of Cockpit to a file.
  - name: Check Status
    shell: systemctl status cockpit > /tmp/cockpit.status
...