---

    - debug:
        var: hostname
    - debug:
        var: port
    - name: Get a cert from an https port
      get_certificate:
        host: "{{ hostname }}"
        port: "{{ port }}"
        # delegate_to: localhost
      run_once: false
      register: cert
    - debug:
        var: cert.not_after
    - name: How many days until cert expires
      debug:
        msg: "{{ hostname }} cert expires in: {{ expire_days }} days."
      vars:
        expire_days: "{{ (( cert.not_after | to_datetime('%Y%m%d%H%M%SZ')) - (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) ).days }}"
      register: result
    - name: reg_results
      set_fact: 
        results: "{{ results + [ result.msg ] }}"

    